language: go

go:
    - 1.12.1

env:
    global:
        - GO111MODULE=on

install:
    - ${TRAVIS_BUILD_DIR}/scripts/build.sh

script:
    - SOURCE_DIR=$(pwd)/product go test -v ./...

notifications:
    slack:
        rooms:
            - privatix:ntmw2wh4PAHoodqtMc95KFDt#dapp-tech
